In [1]:
import pandas as pd
import numpy as np



In [2]:
df = pd.read_csv("stock.csv", encoding="latin1")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 5 columns):
script       39 non-null object
marketcap    39 non-null object
quarter      39 non-null object
year         39 non-null int64
hour         39 non-null int64
dtypes: int64(2), object(3)
memory usage: 1.6+ KB


In [4]:
df = pd.get_dummies(columns=['script'], data=df, drop_first=True)
df = pd.get_dummies(columns=['marketcap'], data=df, drop_first=True)
df = pd.get_dummies(columns=['quarter'], data=df, drop_first=True)

In [5]:
hour = df['hour']
df.drop('hour', axis=1, inplace=True)
df = pd.concat([df, hour], axis=1)
X = df.iloc[:,:-1]
y = df['hour']


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)


In [7]:
from sklearn.svm import SVC

In [8]:
model = SVC()

In [9]:
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
pred = model.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix

In [12]:
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          6       0.00      0.00      0.00         1
          7       0.00      0.00      0.00         1
          9       0.00      0.00      0.00         1
         10       0.00      0.00      0.00         5
         11       0.27      0.75      0.40         4
         15       1.00      1.00      1.00         1

avg / total       0.16      0.31      0.20        13



E:\ML\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [13]:
from sklearn.grid_search import GridSearchCV

E:\ML\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
E:\ML\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [14]:
param_grid = {'C': [0.01, 0.1, 1, 10, 100, 1000, 10000], 'gamma': [0.1, 1, 0.1, 0.01, 0.001, 0.0001, 0.00001]}

In [15]:
grid = GridSearchCV(SVC(), param_grid, verbose=3)

In [16]:
grid.fit(X_train, y_train)

E:\ML\Anaconda3\lib\site-packages\sklearn\cross_validation.py:553: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=3.
  % (min_labels, self.n_folds)), Warning)
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


Fitting 3 folds for each of 49 candidates, totalling 147 fits
[CV] C=0.01, gamma=0.1 ...............................................
[CV] ...................... C=0.01, gamma=0.1, score=0.363636 -   0.0s
[CV] C=0.01, gamma=0.1 ...............................................
[CV] ...................... C=0.01, gamma=0.1, score=0.400000 -   0.0s
[CV] C=0.01, gamma=0.1 ...............................................
[CV] ...................... C=0.01, gamma=0.1, score=0.600000 -   0.0s
[CV] C=0.01, gamma=1 .................................................
[CV] ........................ C=0.01, gamma=1, score=0.363636 -   0.0s
[CV] C=0.01, gamma=1 .................................................
[CV] ........................ C=0.01, gamma=1, score=0.400000 -   0.0s
[CV] C=0.01, gamma=1 .................................................
[CV] ........................ C=0.01, gamma=1, score=0.600000 -   0.0s
[CV] C=0.01, gamma=0.1 ...............................................
[CV] ..........

[CV] .......................... C=10, gamma=1, score=0.363636 -   0.0s
[CV] C=10, gamma=1 ...................................................
[CV] .......................... C=10, gamma=1, score=0.300000 -   0.0s
[CV] C=10, gamma=1 ...................................................
[CV] .......................... C=10, gamma=1, score=0.600000 -   0.0s
[CV] C=10, gamma=0.1 .................................................
[CV] ........................ C=10, gamma=0.1, score=0.363636 -   0.0s
[CV] C=10, gamma=0.1 .................................................
[CV] ........................ C=10, gamma=0.1, score=0.300000 -   0.0s
[CV] C=10, gamma=0.1 .................................................
[CV] ........................ C=10, gamma=0.1, score=0.200000 -   0.0s
[CV] C=10, gamma=0.01 ................................................
[CV] ....................... C=10, gamma=0.01, score=0.454545 -   0.0s
[CV] C=10, gamma=0.01 ................................................
[CV] .

[CV] ....................... C=10000, gamma=1, score=0.300000 -   0.0s
[CV] C=10000, gamma=1 ................................................
[CV] ....................... C=10000, gamma=1, score=0.600000 -   0.0s
[CV] C=10000, gamma=0.1 ..............................................
[CV] ..................... C=10000, gamma=0.1, score=0.363636 -   0.0s
[CV] C=10000, gamma=0.1 ..............................................
[CV] ..................... C=10000, gamma=0.1, score=0.300000 -   0.0s
[CV] C=10000, gamma=0.1 ..............................................
[CV] ..................... C=10000, gamma=0.1, score=0.200000 -   0.0s
[CV] C=10000, gamma=0.01 .............................................
[CV] .................... C=10000, gamma=0.01, score=0.545455 -   0.0s
[CV] C=10000, gamma=0.01 .............................................
[CV] .................... C=10000, gamma=0.01, score=0.400000 -   0.0s
[CV] C=10000, gamma=0.01 .............................................
[CV] .

[Parallel(n_jobs=1)]: Done 147 out of 147 | elapsed:    1.7s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': [0.01, 0.1, 1, 10, 100, 1000, 10000], 'gamma': [0.1, 1, 0.1, 0.01, 0.001, 0.0001, 1e-05]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=3)

In [17]:
grid.best_params_

{'C': 1000, 'gamma': 0.001}

In [18]:
grid.best_estimator_

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [19]:
grid_predictions = grid.predict(X_test)

In [20]:
print(confusion_matrix(y_test, grid_predictions))

[[0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [1 0 0 2 1 1]
 [1 1 0 0 2 0]
 [0 0 0 0 0 1]]


In [21]:
print(classification_report(y_test, grid_predictions))

             precision    recall  f1-score   support

          6       0.00      0.00      0.00         1
          7       0.00      0.00      0.00         1
          9       0.00      0.00      0.00         1
         10       1.00      0.40      0.57         5
         11       0.33      0.50      0.40         4
         15       0.50      1.00      0.67         1

avg / total       0.53      0.38      0.39        13



E:\ML\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
