In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [21]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [22]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7352 entries, 0 to 7351
Columns: 563 entries, tBodyAcc-mean()-X to Activity
dtypes: float64(561), int64(1), object(1)
memory usage: 31.6+ MB


In [23]:
df_train.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X    ...     \
0         -0.923527         -0.934724    ...      
1         -0.957686         -0.943068    ...      
2         -0.977469         -0.938692    ...      
3         -0.989302         -0.938692    ...      
4         -0.990441         -0.942469    ...      

   fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                        -0.710304                    -0.112754   
1                        -0.861499                     0.053477   
2                        -0.760104                    -0.118559   
3                        -0.482845                    -0.036788   
4                        -0.699205                     0.123320   

   angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
0                              0.030400                         -0.464761   
1                             -0.007435                         -0.732626   
2                              0.177899                          0.100699   
3                             -0.012892                          0.640011   
4                              0.122542                          0.693578   

   angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
0                             -0.018446             -0.841247   
1                              0.703511             -0.844788   
2                              0.808529             -0.848933   
3                             -0.485366             -0.848649   
4                             -0.615971             -0.847865   

   angle(Y,gravityMean)  angle(Z,gravityMean)  subject  Activity  
0              0.179941             -0.058627        1  STANDING  
1              0.180289             -0.054317        1  STANDING  
2              0.180637             -0.049118        1  STANDING  
3              0.181935             -0.047663        1  STANDING  
4              0.185151             -0.043892        1  STANDING  

[5 rows x 563 columns]

In [24]:
def change_Activity(cols):
    Activity = cols[0]
    
    if Activity == 'STANDING':
        return 1
    if Activity == 'SITTING' :
        return 2
    if Activity == 'LAYING':
        return 3
    if Activity == 'WALKING' :
        return 4
    if Activity == 'WALKING_DOWNSTAIRS':
        return 5
    if Activity == 'WALKING_UPSTAIRS' :
        return 6

In [25]:
 df_train['Activity'] = df_train[['Activity']].apply(change_Activity, axis=1)
 df_test['Activity'] = df_test[['Activity']].apply(change_Activity, axis=1)

In [26]:
df_test.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.257178          -0.023285          -0.014654         -0.938404   
1           0.286027          -0.013163          -0.119083         -0.975415   
2           0.275485          -0.026050          -0.118152         -0.993819   
3           0.270298          -0.032614          -0.117520         -0.994743   
4           0.274833          -0.027848          -0.129527         -0.993852   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.920091         -0.667683         -0.952501         -0.925249   
1         -0.967458         -0.944958         -0.986799         -0.968401   
2         -0.969926         -0.962748         -0.994403         -0.970735   
3         -0.973268         -0.967091         -0.995274         -0.974471   
4         -0.967445         -0.978295         -0.994111         -0.965953   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X    ...     \
0         -0.674302         -0.894088    ...      
1         -0.945823         -0.894088    ...      
2         -0.963483         -0.939260    ...      
3         -0.968897         -0.938610    ...      
4         -0.977346         -0.938610    ...      

   fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                        -0.705974                     0.006462   
1                        -0.594944                    -0.083495   
2                        -0.640736                    -0.034956   
3                        -0.736124                    -0.017067   
4                        -0.846595                    -0.002223   

   angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
0                              0.162920                         -0.825886   
1                              0.017500                         -0.434375   
2                              0.202302                          0.064103   
3                              0.154438                          0.340134   
4                             -0.040046                          0.736715   

   angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
0                              0.271151             -0.720009   
1                              0.920593             -0.698091   
2                              0.145068             -0.702771   
3                              0.296407             -0.698954   
4                             -0.118545             -0.692245   

   angle(Y,gravityMean)  angle(Z,gravityMean)  subject  Activity  
0              0.276801             -0.057978        2         1  
1              0.281343             -0.083898        2         1  
2              0.280083             -0.079346        2         1  
3              0.284114             -0.077108        2         1  
4              0.290722             -0.073857        2         1  

[5 rows x 563 columns]

In [27]:
    from sklearn.preprocessing import StandardScaler
    scaler_train = StandardScaler()

In [28]:
scaler_train.fit(df_train.drop("Activity", axis=1))
scaled_features_train = scaler_train.transform(df_train.drop("Activity", axis=1))
df_feat_train = pd.DataFrame(scaled_features_train, columns=df_train.columns[:-1])

In [29]:
scaler_test = StandardScaler()
scaler_test.fit(df_test.drop("Activity", axis=1))
scaled_features_test = scaler_test.transform(df_test.drop("Activity", axis=1))
df_feat_test = pd.DataFrame(scaled_features_test, columns=df_test.columns[:-1])

In [30]:
df_feat_train.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.200642          -0.063683          -0.419628         -0.868814   
1           0.055948           0.031486          -0.253908         -0.875426   
2           0.073515          -0.043416          -0.076295         -0.869039   
3           0.066696          -0.208422          -0.249712         -0.870626   
4           0.030469           0.027587          -0.109848         -0.875188   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.939441         -0.737529         -0.859817         -0.939019   
1         -0.923902         -0.849304         -0.868531         -0.921998   
2         -0.907760         -0.893785         -0.863137         -0.898854   
3         -0.940022         -0.921805         -0.864503         -0.938124   
4         -0.934878         -0.921343         -0.867384         -0.931789   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X    ...     \
0         -0.766437         -0.856036    ...      
1         -0.848928         -0.871359    ...      
2         -0.896701         -0.863323    ...      
3         -0.925279         -0.863323    ...      
4         -0.928028         -0.870260    ...      

   fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
0                         0.025960                        -0.276399   
1                        -0.897357                        -0.767990   
2                        -0.260878                        -0.438316   
3                         0.591045                         0.463155   
4                        -0.138515                        -0.240313   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.360603                              0.062940   
1                     0.133011                             -0.021461   
2                    -0.377840                              0.391976   
3                    -0.135025                             -0.033637   
4                     0.340406                              0.268486   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.778427                             -0.026080   
1                         -1.218805                              1.484470   
2                          0.151207                              1.704201   
3                          1.037851                             -1.003019   
4                          1.125918                             -1.276282   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)   subject  
0             -0.687219              0.407946             -0.007568 -1.828851  
1             -0.694138              0.409117              0.007875 -1.828851  
2             -0.702239              0.410288              0.026502 -1.828851  
3             -0.701684              0.414650              0.031714 -1.828851  
4             -0.700152              0.425463              0.045225 -1.828851  

[5 rows x 562 columns]

In [31]:
X_train = df_feat_train
y_train = df_train['Activity']

In [32]:
X_test = df_feat_test
y_test = df_test['Activity']

In [33]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [34]:
pred = model.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix, classification_report

In [36]:
print(confusion_matrix(y_test,pred))

[[499  33   0   0   0   0]
 [ 40 447   2   0   1   1]
 [  0   0 537   0   0   0]
 [  0   0   0 473  17   6]
 [  0   0   0   5 393  22]
 [  0   0   0   5   1 465]]


In [37]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          1       0.93      0.94      0.93       532
          2       0.93      0.91      0.92       491
          3       1.00      1.00      1.00       537
          4       0.98      0.95      0.97       496
          5       0.95      0.94      0.94       420
          6       0.94      0.99      0.96       471

avg / total       0.96      0.95      0.95      2947

