In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [21]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [22]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7352 entries, 0 to 7351
Columns: 563 entries, tBodyAcc-mean()-X to Activity
dtypes: float64(561), int64(2)
memory usage: 31.6 MB


In [23]:
df_train.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X    ...     \
0         -0.923527         -0.934724    ...      
1         -0.957686         -0.943068    ...      
2         -0.977469         -0.938692    ...      
3         -0.989302         -0.938692    ...      
4         -0.990441         -0.942469    ...      

   fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                        -0.710304                    -0.112754   
1                        -0.861499                     0.053477   
2                        -0.760104                    -0.118559   
3                        -0.482845                    -0.036788   
4                        -0.699205                     0.123320   

   angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
0                              0.030400                         -0.464761   
1                             -0.007435                         -0.732626   
2                              0.177899                          0.100699   
3                             -0.012892                          0.640011   
4                              0.122542                          0.693578   

   angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
0                             -0.018446             -0.841247   
1                              0.703511             -0.844788   
2                              0.808529             -0.848933   
3                             -0.485366             -0.848649   
4                             -0.615971             -0.847865   

   angle(Y,gravityMean)  angle(Z,gravityMean)  subject  Activity  
0              0.179941             -0.058627        1         0  
1              0.180289             -0.054317        1         0  
2              0.180637             -0.049118        1         0  
3              0.181935             -0.047663        1         0  
4              0.185151             -0.043892        1         0  

[5 rows x 563 columns]

In [12]:
# def change_Activity(cols):
#    Activity = cols[0]
#    
#    if Activity == 'STANDING':
#        return 1
#    if Activity == 'SITTING' :
#        return 2
#    if Activity == 'LAYING':
#        return 3
#    if Activity == 'WALKING' :
#        return 4
#    if Activity == 'WALKING_DOWNSTAIRS':
#        return 5
#    if Activity == 'WALKING_UPSTAIRS' :
#        return 6

In [20]:
# df_train['Activity'] = df_train[['Activity']].apply(change_Activity, axis=1)
# df_test['Activity'] = df_test[['Activity']].apply(change_Activity, axis=1)

In [24]:
df_test.tail()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
2942           0.310155          -0.053391          -0.099109   
2943           0.363385          -0.039214          -0.105915   
2944           0.349966           0.030077          -0.115788   
2945           0.237594           0.018467          -0.096499   
2946           0.153627          -0.018437          -0.137018   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
2942         -0.287866         -0.140589         -0.215088         -0.356083   
2943         -0.305388          0.028148         -0.196373         -0.373540   
2944         -0.329638         -0.042143         -0.250181         -0.388017   
2945         -0.323114         -0.229775         -0.207574         -0.392380   
2946         -0.330046         -0.195253         -0.164339         -0.430974   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X    ...     \
2942         -0.148775         -0.232057          0.185361    ...      
2943         -0.030036         -0.270237          0.185361    ...      
2944         -0.133257         -0.347029          0.007471    ...      
2945         -0.279610         -0.289477          0.007471    ...      
2946         -0.218295         -0.229933         -0.111527    ...      

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
2942                        -0.750809                    -0.337422   
2943                        -0.700274                    -0.736701   
2944                        -0.467179                    -0.181560   
2945                        -0.617737                     0.444558   
2946                        -0.436940                     0.598808   

      angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
2942                              0.346295                          0.884904   
2943                             -0.372889                         -0.657421   
2944                              0.088574                          0.696663   
2945                             -0.819188                          0.929294   
2946                             -0.287951                          0.876030   

      angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
2942                             -0.698885             -0.651732   
2943                              0.322549             -0.655181   
2944                              0.363139             -0.655357   
2945                             -0.008398             -0.659719   
2946                             -0.024965             -0.660080   

      angle(Y,gravityMean)  angle(Z,gravityMean)  subject  Activity  
2942              0.274627              0.184784       24         5  
2943              0.273578              0.182412       24         5  
2944              0.274479              0.181184       24         5  
2945              0.264782              0.187563       24         5  
2946              0.263936              0.188103       24         5  

[5 rows x 563 columns]

In [26]:
from sklearn.preprocessing import StandardScaler
scaler_train = StandardScaler()

In [27]:
scaler_train.fit(df_train.drop("Activity", axis=1))
scaled_features_train = scaler_train.transform(df_train.drop("Activity", axis=1))
df_feat_train = pd.DataFrame(scaled_features_train, columns=df_train.columns[:-1])

In [28]:
scaler_test = StandardScaler()
scaler_test.fit(df_test.drop("Activity", axis=1))
scaled_features_test = scaler_test.transform(df_test.drop("Activity", axis=1))
df_feat_test = pd.DataFrame(scaled_features_test, columns=df_test.columns[:-1])

In [30]:
df_feat_train.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.200642          -0.063683          -0.419628         -0.868814   
1           0.055948           0.031486          -0.253908         -0.875426   
2           0.073515          -0.043416          -0.076295         -0.869039   
3           0.066696          -0.208422          -0.249712         -0.870626   
4           0.030469           0.027587          -0.109848         -0.875188   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.939441         -0.737529         -0.859817         -0.939019   
1         -0.923902         -0.849304         -0.868531         -0.921998   
2         -0.907760         -0.893785         -0.863137         -0.898854   
3         -0.940022         -0.921805         -0.864503         -0.938124   
4         -0.934878         -0.921343         -0.867384         -0.931789   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X    ...     \
0         -0.766437         -0.856036    ...      
1         -0.848928         -0.871359    ...      
2         -0.896701         -0.863323    ...      
3         -0.925279         -0.863323    ...      
4         -0.928028         -0.870260    ...      

   fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
0                         0.025960                        -0.276399   
1                        -0.897357                        -0.767990   
2                        -0.260878                        -0.438316   
3                         0.591045                         0.463155   
4                        -0.138515                        -0.240313   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.360603                              0.062940   
1                     0.133011                             -0.021461   
2                    -0.377840                              0.391976   
3                    -0.135025                             -0.033637   
4                     0.340406                              0.268486   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.778427                             -0.026080   
1                         -1.218805                              1.484470   
2                          0.151207                              1.704201   
3                          1.037851                             -1.003019   
4                          1.125918                             -1.276282   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)   subject  
0             -0.687219              0.407946             -0.007568 -1.828851  
1             -0.694138              0.409117              0.007875 -1.828851  
2             -0.702239              0.410288              0.026502 -1.828851  
3             -0.701684              0.414650              0.031714 -1.828851  
4             -0.700152              0.425463              0.045225 -1.828851  

[5 rows x 562 columns]

In [31]:
df_feat_test.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0          -0.277708          -0.210631           2.193076         -0.787267   
1           0.198660           0.182591          -0.250264         -0.876984   
2           0.024587          -0.318055          -0.228485         -0.921598   
3          -0.061057          -0.573037          -0.213709         -0.923837   
4           0.013823          -0.387881          -0.494639         -0.921679   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.833212         -0.093444         -0.808091         -0.839013   
1         -0.929061         -0.858050         -0.897145         -0.928949   
2         -0.934054         -0.907107         -0.916891         -0.933813   
3         -0.940817         -0.919082         -0.919152         -0.941599   
4         -0.929036         -0.949979         -0.916133         -0.923846   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X    ...     \
0         -0.104178         -0.824746    ...      
1         -0.863269         -0.824746    ...      
2         -0.912639         -0.910982    ...      
3         -0.927776         -0.909740    ...      
4         -0.951396         -0.909740    ...      

   fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
0                        -0.166391                        -0.344765   
1                         0.491021                         0.012257   
2                         0.274821                        -0.134989   
3                        -0.210678                        -0.441714   
4                        -0.810527                        -0.796939   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                     0.003566                              0.357573   
1                    -0.264092                              0.030787   
2                    -0.119671                              0.446072   
3                    -0.066443                              0.338512   
4                    -0.022276                             -0.098529   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -1.363900                              0.575487   
1                         -0.747232                              1.871192   
2                          0.037919                              0.323938   
3                          0.472695                              0.625874   
4                          1.097348                             -0.201999   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)   subject  
0             -0.404790              0.622723             -0.038348 -1.580825  
1             -0.361739              0.636731             -0.145709 -1.580825  
2             -0.370932              0.632845             -0.126855 -1.580825  
3             -0.363434              0.645276             -0.117585 -1.580825  
4             -0.350256              0.665657             -0.104118 -1.580825  

[5 rows x 562 columns]

In [32]:
X_train = df_feat_train
y_train = df_train['Activity']

In [33]:
X_test = df_feat_test
y_test = df_test['Activity']

In [34]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [35]:
pred = model.predict(X_test)

In [36]:
from sklearn.metrics import confusion_matrix, classification_report

In [37]:
print(confusion_matrix(y_test,pred))

[[499  33   0   0   0   0]
 [ 40 447   2   0   1   1]
 [  0   0 537   0   0   0]
 [  0   0   0 473  17   6]
 [  0   0   0   5 393  22]
 [  0   0   0   5   1 465]]


In [38]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.93      0.94      0.93       532
          1       0.93      0.91      0.92       491
          2       1.00      1.00      1.00       537
          3       0.98      0.95      0.97       496
          4       0.95      0.94      0.94       420
          5       0.94      0.99      0.96       471

avg / total       0.96      0.95      0.95      2947

